export enum QuizTypes {
    FETCH_ALL_QUIZES = 'FETCH_ALL_QUIZES',
    FETCH_USER_QUIZES = 'FETCH_USER_QUIZES',
    SET_FORM_PAGE_COUNTER = 'SET_FORM_PAGE_COUNTER',
    // SET_QUESTION_COUNTER = 'SET_QUESTION_COUNTER'
}