export enum QuizTypes {
    FETCH_ALL_QUIZZES = 'FETCH_ALL_QUIZZES',
    FETCH_USER_QUIZZES = 'FETCH_USER_QUIZZES',
    SET_FORM_QUESTIONS = 'SET_FORM_QUESTIONS',
    SET_FORM_COUNTER = 'SET_FORM_COUNTER',
    SET_FORM_COLOR = 'SET_FORM_COLOR',
    SET_FORM_ICON_NAME = 'SET_FORM_ICON_NAME',
    SET_FORM_QUESTIONS_COUNTER = 'SET_FORM_QUESTIONS_COUNTER',
}

