export enum QuizTypes {
    FETCH_ALL_QUIZES = 'FETCH_ALL_QUIZES',
    FETCH_USER_QUIZES = 'FETCH_USER_QUIZES',
    SET_FORM_QUESTIONS = 'SET_FORM_QUESTIONS',
    SET_FORM_COUNTER = 'SET_FORM_COUNTER',
    SET_FORM_COLOR = 'SET_FORM_COLOR',
    SET_FORM_ICON_NAME = 'SET_FORM_ICON_NAME',
}

